version: "1.0"
services:
  app:
    image: sportapp
    ports:
      - 8080:8080
    environment:
      - WORKER_URI=http://worker:9001/

  worker:
    image: sportworker
    ports:
      - 9001:9001
    links:
      - datastore

  datastore:
    image: mongo
    container_name: datastore-service
    restart: always
    command: --quiet --syslog
    expose:
      - "27017"
